remove yellow call on string
erb_lint no longer uses colorize for coloring strings—they've switched to Rainbow. Moreover, if the color gem used here is not in this gem's gemspec its API probably shouldn't be used to avoid issues like this during optimistic gem upgrades `('erb_lint', '~> 0.0.24')`.

```
/usr/local/bundle/gems/pronto-erb_lint-0.1.5/lib/pronto/erb_lint.rb:29:in `load_config': undefined method `yellow' for ".erb-lint.yml not found: using default config":String (NoMethodError)
```